// <auto-generated>
// 生成日時: @GeneratedDate
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace GeneratedClasses
{
    /// <summary>
    /// Excelテーブル '@TableName' のクラス
    /// 親クラスやインターフェースを自由に追加できます
    /// </summary>
    [XmlRoot("Record")]
    public class @TableName : SerializeData
    {
        // ▼ ここにルートクラスの変数が展開されます
@RootProperties

        // ▼ テンプレート側で自由にメソッドや固定変数を追加できます
        public string GetOriginalName()
        {
            return Name.OriginalName;
        }
    }

    // ▼ ここにサブクラス（グループ）の定義が展開されます
@SubClasses
}