// <auto-generated>
// 生成日時: @GeneratedDate
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace XmlData
{
    // ==========================================
    // ルートクラス定義
    // ==========================================
    [XmlRoot("Record")]
    public class @TableName : ISerializeData
    {
@RootProperties

#If(#Contains(@TableName, CardData))
        public void SetCardData(CardData cardData)
        {
            cardData.cardNo = Id;
            cardData.cardOriginalName = Name.OriginalName;
            cardData.cardStatus.Clear();
            cardData.cardProperties.Clear();
#ForAllSubClasses
#ForAllSubClassProperties
#If(#Or(#Eq(@SubClassTagName, Status), #Eq(@SubClassTagName, Properties)))
            cardData.card@SubClassTagName.Add("@SubClassPropertyName", @SubClassTagName.@SubClassPropertyName);
#Endif
#EndForAllSubClassProperties
#EndForAllSubClasses
            cardData.cardDataCollectionName = "#Replace(@TableName, CardData, CardDataCollection)";
        }
#Endif
    }

    // ==========================================
    // サブクラス定義 (二重マクロによる生成)
    // ==========================================
#ForAllSubClasses

    /// <summary>
    /// 元のタグ名: @SubClassTagName
    /// </summary>
    public class @SubClassName
    {
#ForAllSubClassProperties
        [XmlElement("@SubClassPropertyName")]
        public @SubClassPropertyType @SubClassPropertyName { get; set; }
#EndForAllSubClassProperties
    }
#EndForAllSubClasses
}