// <auto-generated>
// 生成日時: @GeneratedDate
// Template_CardDataCollection
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace XmlData
{
    // ==========================================
    // ルートクラス定義
    // ==========================================
    [XmlRoot("Record")]
#If(#Contains(@TableName, CardDataCollection_))
    public class @TableName : IXmlCardDataCollection
#Else
    public class @TableName : IXmlData
#Endif
    {
@RootProperties

#If(#Contains(@TableName, CardDataCollection_))
        public void SetCardDataCollection(CardDataCollection cardDataCollection)
        {
            cardDataCollection.id = Id;
#ForAllSubClasses
#ForAllSubClassProperties
#If(#Eq(@SubClassTagName, Name))
            cardDataCollection.collection@SubClassPropertyName = @SubClassTagName.@SubClassPropertyName;
#Endif
#EndForAllSubClassProperties
#EndForAllSubClasses
            cardData.releaseDate = ReleaseDate;
        }
#Endif
    }

    // ==========================================
    // サブクラス定義 (二重マクロによる生成)
    // ==========================================
#ForAllSubClasses

    /// <summary>
    /// 元のタグ名: @SubClassTagName
    /// </summary>
    public class @SubClassName
    {
#ForAllSubClassProperties
        [XmlElement("@SubClassPropertyName")]
        public @SubClassPropertyType @SubClassPropertyName { get; set; }
#EndForAllSubClassProperties
    }
#EndForAllSubClasses
}